env:
    amd: true
    node: true
    shared-node-browser: true
    browser: true
root: true
parser: "@typescript-eslint/parser"
plugins:
    - "@typescript-eslint"
extends:
    - "eslint:recommended"
    - "plugin:@typescript-eslint/recommended"
    - "plugin:prettier/recommended"
rules:
    "@typescript-eslint/ban-types": off
    "@typescript-eslint/explicit-module-boundary-types": off
    "@typescript-eslint/no-explicit-any": off
    "@typescript-eslint/no-inferrable-types": off
    "@typescript-eslint/no-unused-vars": off
    "@typescript-eslint/triple-slash-reference": off
    "no-case-declarations": off
overrides:
    - files:
          - "*.js"
      rules:
          "@typescript-eslint/no-var-requires": off
